config/routes.rb
Rails.application.routes.draw do
  resources :artists do
    resources :songs, only: [:new, :create]
  end

  resources :songs, only: [:show]

  resources :playlists, except: [:delete]

  get '/auth/spotify/callback', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  validates :name,       presence:   true,
                         uniqueness: true
  validates :image_path, presence:   true

  has_many :songs
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  validates :name, presence: true

  has_many :playlist_songs
  has_many :songs, through: :playlist_songs
end

app/models/playlist_song.rb
class PlaylistSong < ActiveRecord::Base
  belongs_to :song
  belongs_to :playlist
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.find_or_create_from_auth(auth)
    User.find_or_create_by(
      provider: auth["provider"],
      uid: auth["info"]["id"],
      name: auth["info"]["display_name"]
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to @artist
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @artist.update(artist_params)
      redirect_to @artist
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name, :image_path)
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update]
  def index
    @playlists = Playlist.all
  end

  def new
    @playlist = Playlist.new
    @songs    = Song.all
  end

  def create
    @playlist = Playlist.new(playlist_params)
    if @playlist.save
      redirect_to @playlist
    else
      render :new
    end
  end

  def show
  end

  def edit
    @songs = Song.all
  end

  def update
    if @playlist.update(playlist_params)
      redirect_to @playlist
    else
      render :edit
    end
  end

  private

  def set_playlist
    @playlist = Playlist.find(params[:id])
  end

  def playlist_params
    params.require(:playlist).permit(:name, song_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_from_auth(request.env['omniauth.auth'])
    if @user
      session[:user_id] = @user.id
      redirect_to playlists_path
    end
  end

  def destroy
    session.clear
    redirect_to playlists_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def new
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.new
  end

  def create
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.create(song_params)

    redirect_to song_path(@song)
  end

  def show
    @song = Song.find(params[:id])
    @artist = @song.artist
  end

  private

  def song_params
    params.require(:song).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |form| %>

  <%= render partial: "shared/errors", locals: { target: @artist } %>

  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :image_path %>
  <%= form.text_field :image_path %>

  <%= form.submit %>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>

<%= render partial: "form" %>

app/views/artists/index.html.erb
<h1>All Artists</h1>

<ol>
  <% @artists.each do |artist| %>
    <li><%= link_to artist.name, artist %></li>
  <% end %>
</ol>

<%= link_to "New artist", new_artist_path %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render partial: "form" %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<%= image_tag @artist.image_path %>
<%= link_to "Edit Artist", edit_artist_path %>
<%= link_to "Delete Artist", @artist, method: :delete, data: {confirm: "Are you sure you want to delete this artist?"} %>
<%= link_to "New song", new_artist_song_path(@artist) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MixMaster</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <% if current_user %>
      <h3>Welcome, <%= current_user.name %></h3>
      <%= link_to "Sign out", logout_path, method: :delete %>
    <% else %>
      <%= link_to "Sign in with Spotify", "/auth/spotify" %>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>

  <%= render partial: "shared/errors", locals: { target: @playlist } %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <% @songs.each do |song| %>
    <div>
      <%= check_box_tag(:song_ids, song.id, false, :name => 'playlist[song_ids][]', id: "song-#{song.id}") %>
      <%= song.title %>
    </div>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/playlists/edit.html.erb
<h1>Edit Playlist</h1>

<%= render partial: "form" %>

app/views/playlists/index.html.erb
<h1></h1>

<ul>
  <% @playlists.each do |playlist| %>
    <li><%= link_to playlist.name, playlist_path(playlist) %>
    </li>
  <% end %>
</ul>

<%= link_to "New playlist", new_playlist_path %>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render partial: "form" %>

app/views/playlists/show.html.erb
<h1></h1>

<%= @playlist.name %>

<ol>
  <% @playlist.songs.each do |song| %>
    <li><%= link_to song.title, song_path(song) %></li>
  <% end %>
</ol>

<%= link_to "Edit", edit_playlist_path(@playlist) %>

app/views/shared/_errors.html.erb
<% if target.errors.any? %>
  <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this record from being saved:</h2>
  <ul>
    <% target.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<p>Add a new song for <%= @artist.name %></p>

<%= form_for([@artist, @song]) do |f| %>

  <%= render partial: "shared/errors", locals: { target: @song } %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>
<% end %>

app/views/songs/show.html.erb
<%= @song.title %>
<%= link_to @artist.name, @artist %>